letsencrypt:
#  build: .
  image: quay.io/letsencrypt/letsencrypt:latest
  ports:
    - "443:443"
#    - "80:80"
  volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - /var/lib/letsencrypt:/var/lib/letsencrypt
  command: auth
